# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SimpleOS
email: jaaaa@example.com
description: >- # this means to ignore newlines until "baseurl:"
# Learning Journey

Welcome to my learning journey! This page is dedicated to my pursuit of knowledge and skills in various programming topics, including JavaScript, MySQL, Jekyll, and more. I'm using this space to document my progress, share my experiences, and showcase the projects I'm working on to enhance my programming skills.

## About Me

I'm an aspiring programmer eager to dive into the world of web development. My primary areas of focus are:

- **JavaScript (JS)**: I'm exploring JavaScript to build interactive web applications and improve user experiences.
- **MySQL**: I'm delving into database management with MySQL to better understand how data is stored and retrieved.
- **Jekyll**: I'm using Jekyll to create static websites and blogs, learning the ins and outs of this powerful tool.

## Projects

As part of my learning journey, I'll be working on various programming projects. Some of the upcoming projects include:

- A personal website built with Jekyll to showcase my skills and achievements.
- A web app using JavaScript to perform a specific task.
- A database-driven project with MySQL integration.

Follow along as I learn, experiment, and grow as a programmer!


baseurl: "SimpleOS" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mytwitter
github_username:  Angnz

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
